// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcheomrmmdbmlobhxljt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaGVvbXJtbWRibWxvYmh4bGp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDM2NzgsImV4cCI6MjA2NTg3OTY3OH0.KxU5uOIaAxM-KrutMnoENUFAunYMqeonBwgH42WMd8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);